package cn.edu.nju.userstorymappingtool.entity;

import java.io.Serializable;

public class Mapcode implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mapcode.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mapcode.userid
     *
     * @mbg.generated
     */
    private Long userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mapcode.mapid
     *
     * @mbg.generated
     */
    private Long mapid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mapcode.code
     *
     * @mbg.generated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mapcode
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mapcode.id
     *
     * @return the value of mapcode.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mapcode.id
     *
     * @param id the value for mapcode.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mapcode.userid
     *
     * @return the value of mapcode.userid
     *
     * @mbg.generated
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mapcode.userid
     *
     * @param userid the value for mapcode.userid
     *
     * @mbg.generated
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mapcode.mapid
     *
     * @return the value of mapcode.mapid
     *
     * @mbg.generated
     */
    public Long getMapid() {
        return mapid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mapcode.mapid
     *
     * @param mapid the value for mapcode.mapid
     *
     * @mbg.generated
     */
    public void setMapid(Long mapid) {
        this.mapid = mapid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mapcode.code
     *
     * @return the value of mapcode.code
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mapcode.code
     *
     * @param code the value for mapcode.code
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapcode
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userid=").append(userid);
        sb.append(", mapid=").append(mapid);
        sb.append(", code=").append(code);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}