package cn.edu.nju.userstorymappingtool.entity;

import java.io.Serializable;

public class Storymap implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storymap.mapid
     *
     * @mbg.generated
     */
    private Long mapid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storymap.userid
     *
     * @mbg.generated
     */
    private Long userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storymap.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storymap.createdtime
     *
     * @mbg.generated
     */
    private Long createdtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storymap.isdeleted
     *
     * @mbg.generated
     */
    private Short isdeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storymap.deletedtime
     *
     * @mbg.generated
     */
    private Long deletedtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storymap.modifiedtime
     *
     * @mbg.generated
     */
    private Long modifiedtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storymap.releasenum
     *
     * @mbg.generated
     */
    private Integer releasenum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storymap.storynum
     *
     * @mbg.generated
     */
    private Integer storynum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storymap.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table storymap
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storymap.mapid
     *
     * @return the value of storymap.mapid
     *
     * @mbg.generated
     */
    public Long getMapid() {
        return mapid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storymap.mapid
     *
     * @param mapid the value for storymap.mapid
     *
     * @mbg.generated
     */
    public void setMapid(Long mapid) {
        this.mapid = mapid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storymap.userid
     *
     * @return the value of storymap.userid
     *
     * @mbg.generated
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storymap.userid
     *
     * @param userid the value for storymap.userid
     *
     * @mbg.generated
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storymap.name
     *
     * @return the value of storymap.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storymap.name
     *
     * @param name the value for storymap.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storymap.createdtime
     *
     * @return the value of storymap.createdtime
     *
     * @mbg.generated
     */
    public Long getCreatedtime() {
        return createdtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storymap.createdtime
     *
     * @param createdtime the value for storymap.createdtime
     *
     * @mbg.generated
     */
    public void setCreatedtime(Long createdtime) {
        this.createdtime = createdtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storymap.isdeleted
     *
     * @return the value of storymap.isdeleted
     *
     * @mbg.generated
     */
    public Short getIsdeleted() {
        return isdeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storymap.isdeleted
     *
     * @param isdeleted the value for storymap.isdeleted
     *
     * @mbg.generated
     */
    public void setIsdeleted(Short isdeleted) {
        this.isdeleted = isdeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storymap.deletedtime
     *
     * @return the value of storymap.deletedtime
     *
     * @mbg.generated
     */
    public Long getDeletedtime() {
        return deletedtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storymap.deletedtime
     *
     * @param deletedtime the value for storymap.deletedtime
     *
     * @mbg.generated
     */
    public void setDeletedtime(Long deletedtime) {
        this.deletedtime = deletedtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storymap.modifiedtime
     *
     * @return the value of storymap.modifiedtime
     *
     * @mbg.generated
     */
    public Long getModifiedtime() {
        return modifiedtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storymap.modifiedtime
     *
     * @param modifiedtime the value for storymap.modifiedtime
     *
     * @mbg.generated
     */
    public void setModifiedtime(Long modifiedtime) {
        this.modifiedtime = modifiedtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storymap.releasenum
     *
     * @return the value of storymap.releasenum
     *
     * @mbg.generated
     */
    public Integer getReleasenum() {
        return releasenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storymap.releasenum
     *
     * @param releasenum the value for storymap.releasenum
     *
     * @mbg.generated
     */
    public void setReleasenum(Integer releasenum) {
        this.releasenum = releasenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storymap.storynum
     *
     * @return the value of storymap.storynum
     *
     * @mbg.generated
     */
    public Integer getStorynum() {
        return storynum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storymap.storynum
     *
     * @param storynum the value for storymap.storynum
     *
     * @mbg.generated
     */
    public void setStorynum(Integer storynum) {
        this.storynum = storynum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storymap.description
     *
     * @return the value of storymap.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storymap.description
     *
     * @param description the value for storymap.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storymap
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", mapid=").append(mapid);
        sb.append(", userid=").append(userid);
        sb.append(", name=").append(name);
        sb.append(", createdtime=").append(createdtime);
        sb.append(", isdeleted=").append(isdeleted);
        sb.append(", deletedtime=").append(deletedtime);
        sb.append(", modifiedtime=").append(modifiedtime);
        sb.append(", releasenum=").append(releasenum);
        sb.append(", storynum=").append(storynum);
        sb.append(", description=").append(description);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}