package cn.edu.nju.userstorymappingtool.dao;

import cn.edu.nju.userstorymappingtool.entity.Map;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface MapMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long mapid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map
     *
     * @mbg.generated
     */
    int insert(Map record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map
     *
     * @mbg.generated
     */
    Map selectByPrimaryKey(Long mapid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map
     *
     * @mbg.generated
     */
    List<Map> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Map record);
}