package cn.edu.nju.userstorymappingtool.dao;

import cn.edu.nju.userstorymappingtool.entity.Storymap;
import java.util.List;

public interface StorymapMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storymap
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long mapid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storymap
     *
     * @mbg.generated
     */
    int insert(Storymap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storymap
     *
     * @mbg.generated
     */
    Storymap selectByPrimaryKey(Long mapid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storymap
     *
     * @mbg.generated
     */
    List<Storymap> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storymap
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Storymap record);

    List<Storymap> selectAllMapsByUserid(Long userid);
}